#' chemdiv: A package for analysing phytochemical diversity
#'
#' The chemdiv package contains various functions for convenient analyses
#' of phytochemical (and similar) data on e.g. floral scent,
#' green leaf volatiles and chemical defence compounds.
#' Analyses are centered around calculations of diversity and
#' molecular/biosynthetic similarity, both separately and combined.
#' It will work best for datasets, commonly generated by chemical ecologists
#' using GC-MS, LC-MS or similar, where all or most compounds in the dataset
#' have been identified.
#'
#' Two datasets are needed to use the full set of analyses
#' included in the package. The first dataset should contain data on the
#' relative proportions of different compounds (columns)
#' in different samples (rows). The second dataset should contain the
#' name, (Isomeric?) SMILES and InChIKey of all the compounds that are included
#' in the first dataset (in each of three columns in a data frame).
#' SMILES and InChIKey are chemical identifiers that are easily obtained
#' for each compound by searching
#' PubChem \url{https://pubchem.ncbi.nlm.nih.gov/}. The user is urged to
#' do this manually as compound lists often contain compounds wrongly named,
#' wrongly formatted, under various synonyms etc. which prevents easy
#' translation of compounds names to SMILES and InChIKey automatically.
#'
#' @section Compound classification and dissimilarity:
#' \code{\link{NPCTable}}
#' \code{\link{compDis}}
#'
#' @section Diversity calculations:
#' \code{\link{calcDiv}}
#' \code{\link{calcBetaDiv}}
#' \code{\link{calcDivProf}}
#'
#' @section Sample dissimilarities:
#' \code{\link{sampleDis}}
#'
#' @section Molecular network and properties:
#' \code{\link{molNet}}
#'
#' @section Chemodiversity and network plots:
#' \code{\link{molNetPlot}}
#' \code{\link{chemDivPlot}}
#'
#' @author List authors here
#'
#' @references A bunch probably
#'
#' @importFrom rlang .data
#'
#' @docType package
#' @name chemdiv
NULL
