#' Arabis alpina floral scent data
#'
#' A dataset with (proportional) floral scent data from three populations of
#' the plant species Arabis alpina.
#'
#' @format A data frame with 87 rows and 16 columns. Each row is a sample,
#' first column is population, the other columns are scent compounds.
#'
#' @source \url{https://doi.org/10.1093/aob/mcab007}
"alpinaDataSubset"

#' Arabis alpina floral scent compounds
#'
#' A dataset listing the compounds found in \code{\link{alpinaDataSubset}}
#'
#' @format A data frame with 15 rows and 3 columns. Each row is a compound.
#' First column is a common name of the compound, second column is the
#' SMILES (Simplified Molecular-Input Line-Entry System) specification,
#' third column is the InChIKey (International Chemical Identifier).
#'
#' @source \url{https://doi.org/10.1093/aob/mcab007}
"alpinaCompSubset"

#' Minimal sample dataset
#'
#' A minimal made up dataset with floral scent data.
#'
#' @format A data frame with 4 rows and 3 columns. Each row is a sample,
#' each column is a scent compound.
#'
"minimalSampData"

#' Minimal compound dataset
#'
#' A minimal dataset with three floral scent compounds.
#'
#' @format A data frame with 3 rows and 3 columns. Each row is a compound.
#' First column is a common name of the compound, second column is the
#' SMILES (Simplified Molecular-Input Line-Entry System) specification,
#' third column is the InChIKey (International Chemical Identifier).
#'
"minimalCompData"

#' Minimal compound dissimilarity matrix
#'
#' A minimal matrix with compound dissimilarities calculated from
#' PubChem Fingerprints for the compounds in \code{\link{minimalCompData}}
#'
#' @format A 3x3 compound dissimilarity matrix
#'
"minimalCompDis"

#' Minimal sample dissimilarity matrix
#'
#' A minimal matrix with sample dissimilarities calculated from
#' \code{\link{minimalSampData}} and \code{\link{minimalCompDis}}
#' using UniFracs with alpha = 0.5
#' (and UPGMA clustering)
#'
#' @format A 4x4 sample dissimilarity matrix
#'
"minimalSampDis"

#' Minimal NPClassifier table
#'
#' A minimal table with the NPClassifier pathways, superclasses and classes,
#' along with the compound names, smiles and inchikeys. Generated by
#' the \code{\link{NPCTable}} function
#'
#' @format A dataframe with 3 compounds and their NPClassifier classifications
#'
"minimalNPCTable"

#' Minimal molecular network
#'
#' A minimal molecular network. Generated by the \code{\link{molNet}} function
#'
#' @format A tbl_graph with 3 nodes and 4 edges
#'
"minimalMolNet"
